logger:
  backup_count: 5
  datefmt: '%Y-%m-%d %H:%M:%S'
  encoding: utf-8
  filemode: a
  filename: logs/blackbox.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: DEBUG
  max_bytes: 10485760
options:
  debug: false
  difficulty: 0
  sound: true
window:
  height: 600
  icon: assets/icon.png
  title: Blackbox
  width: 800
